version: '3.8'

services:
  db:
    image: mariadb:latest
    container_name: mariadb-container
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: tresordb
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: unless-stopped
    networks:
      - tresor_app

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-app-backend
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://db:3306/tresordb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=1234
      - CROSS_ORIGIN=http://localhost:80
    restart: unless-stopped
    command: ["/usr/local/bin/wait-for-db.sh", "db:3306", "--", "java", "-jar", "*.jar"]
    networks:
      - tresor_app
    volumes:
      - .:/workspace

networks:
  tresor_app:

volumes:
  mariadb_data:
  workspace: